INSERT INTO `categories` (`id`, `parent_id`, `title`, `created_at`, `updated_at`) VALUES
                                                                                      (1,	NULL,	'Банкротства',	NULL,	NULL),
                                                                                      (2,	NULL,	'Партнерские проекты',	NULL,	NULL),
                                                                                      (3,	NULL,	'Картотека',	NULL,	NULL),
                                                                                      (4,	NULL,	'Конференции',	NULL,	NULL),
                                                                                      (5,	1,	'Университетъ',	NULL,	NULL),
                                                                                      (6,	5,	'Подписка',	NULL,	NULL),
                                                                                      (7,	5,	'Реклама',	NULL,	NULL),
                                                                                      (8,	5,	'Фотоагентство',	NULL,	NULL),
                                                                                      (9,	5,	'Газета',	NULL,	NULL),
                                                                                      (10,	4,	'Weekend',	NULL,	NULL),
                                                                                      (11,	5,	'Приложения',	NULL,	NULL),
                                                                                      (12,	4,	'Автопилот',	NULL,	NULL),
                                                                                      (13,	1,	'Наука',	NULL,	NULL),
                                                                                      (14,	4,	'Деньги',	NULL,	NULL),
                                                                                      (15,	14,	'Регионы',	NULL,	NULL),
                                                                                      (16,	2,	'Экономика',	NULL,	NULL),
                                                                                      (17,	16,	'Политика',	NULL,	NULL),
                                                                                      (18,	3,	'Мир',	NULL,	NULL),
                                                                                      (19,	16,	'Бизнес',	NULL,	NULL),
                                                                                      (20,	18,	'Финансы',	NULL,	NULL),
                                                                                      (21,	18,	'Потребительский рынок',	NULL,	NULL),
                                                                                      (22,	3,	'Телекоммуникации',	NULL,	NULL),
                                                                                      (23,	2,	'Общество',	NULL,	NULL),
                                                                                      (24,	14,	'Происшествия',	NULL,	NULL),
                                                                                      (25,	12,	'Культура',	NULL,	NULL),
                                                                                      (26,	5,	'Спорт',	NULL,	NULL),
                                                                                      (27,	3,	'Hi-Tech',	NULL,	NULL),
                                                                                      (28,	23,	'Авто',	NULL,	NULL),
                                                                                      (29,	1,	'Стиль',	NULL,	NULL),
                                                                                      (30,	2,	'Темы',	NULL,	NULL),
                                                                                      (31,	29,	'Тенденции',	NULL,	NULL),
                                                                                      (32,	2,	'Мультимедиа',	NULL,	NULL),
                                                                                      (33,	23,	'Интервью',	NULL,	NULL),
                                                                                      (34,	3,	'Справочники',	NULL,	NULL),
                                                                                      (35,	1,	'Самое читаемое',	NULL,	NULL),
                                                                                      (36,	2,	'E-mail рассылки',	NULL,	NULL);